[package]
name = "openai"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
reqwest = {version = "0.11", features = ["json"]}
serde = {version="1.0", features= ["derive"]}
serde_json = "1.0"
thiserror = "1.0.40"
